# Generated by Django 5.1.1 on 2024-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='external_wallet',
            field=models.CharField(blank=True, null=True),
        ),
    ]
