# Generated by Django 5.1.1 on 2024-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_wallet_external_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='external_wallet',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='seed_phrase',
            field=models.CharField(unique=True),
        ),
    ]
