# Generated by Django 5.1.1 on 2024-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_fund_amount_alter_wallet_external_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
