# Generated by Django 5.1.1 on 2024-10-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
