# Generated by Django 5.1.1 on 2024-10-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_slug_wallet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
    ]
